# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Deploy

concurrency: deploy

on:
  push:
    branches:
      - hugo

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Set up cachix
        uses: cachix/cachix-action@master
        with:
          name: viperml
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Checkout
        uses: actions/checkout@main

      - name: Build
        run: cp -vrL $(nix build -L --print-out-paths --no-link) ./public

      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: pages publish --project-name=neohome ./public

